[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tonic = "0.9"
tokio-stream = { version = "0.1", features = ["net"] }
prost = "0.11"
tower = "0.4"
get_if_addrs = "0.5"

[build-dependencies]
tonic-build = "0.9"
